import buildSrc.GroovydocForking

plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    alias libs.plugins.gradleutils
    alias libs.plugins.gitversion
    alias libs.plugins.licenser
}

ext.buildType = project.hasProperty('buildType') ? buildType : 'RELEASE'
ext.buildNumber = project.hasProperty('buildNumber') ? buildNumber : '0'
ext.ciSystem = project.hasProperty('ciSystem') ? ciSystem : 'unknown'
ext.commit = project.hasProperty('commit') ? commit : 'unknown'

gradleutils.displayName = 'SpongePowered Mixin Gradle Plugin'
gradleutils.vendor = 'SpongePowered'
description = 'Gradle plugin for SpongePowered Mixin'
group = 'org.spongepowered'
version = buildType == 'SNAPSHOT' ? "${gitversion.info.tag}-SNAPSHOT" : gitversion.tagOffset
final projectUrl = 'https://www.spongepowered.org'

println "Version: $version"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

repositories {
    mavenCentral()
    maven gradleutils.forgeMaven
}

dependencies {
    compileOnly libs.gradle

    implementation libs.guava
    implementation libs.asm.tree
}

tasks.named('processResources', ProcessResources) {
    from 'LICENSE.txt'

    duplicatesStrategy = 'INCLUDE'
}

license {
    ext {
        name = 'MixinGradle'
        organization = gradleutils.vendor.get()
        url = projectUrl
    }
    include '**/*.groovy'
    header = rootProject.file('HEADER.txt')
}

tasks.named('groovydoc', Groovydoc) {
    enabled = false
}

tasks.register('groovydocForked', GroovydocForking) {
    description = 'Generates Groovydoc API documentation for the main source code.'
    group = JavaBasePlugin.DOCUMENTATION_GROUP

    classpath = sourceSets.main.output + sourceSets.main.compileClasspath

    source = sourceSets.main.groovy

    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.named('jar', Jar) {
    manifest.mainAttributes(
        'Built-By': System.properties['user.name'],
        'Created-By': "${System.properties['java.vm.version']} (${System.properties['java.vm.vendor']})",
        "Implementation-Title": project.name,
        "Implementation-Version": "${project.version}+${ciSystem}-b${buildNumber}.git-${commit}",
    )
}

tasks.register('groovydocJar', Jar) {
    dependsOn groovydocForked
    from groovydocForked.destinationDir

    archiveClassifier = 'groovydoc'
}

tasks.named('assemble') {
    dependsOn groovydocJar
}

gradlePlugin {
    website = gitversion.url
    vcsUrl = gitversion.url + '.git'

    plugins.register('mixingradle') {
        id = 'org.spongepowered.mixin'
        implementationClass = 'org.spongepowered.asm.gradle.plugins.MixinGradlePlugin'
        displayName = 'SpongePowered Mixin Gradle Plugin'
        description = 'Gradle plugin for SpongePowered Mixin'
        tags = ['spongepowered', 'sponge', 'mixin']
    }
}

publishing {
    repositories {
        if (buildType == 'RELEASE') {
            if (project.hasProperty('releaseRepo')) {
                maven {
                    credentials {
                        username = project.releaseRepoUsername
                        password = project.releaseRepoPassword
                    }
                    url project.releaseRepo
                }
            }
            if (project.hasProperty('spongeReleaseRepo')) {
                maven {
                    credentials {
                        username = project.spongeUsername
                        password = project.spongePassword
                    }
                    url project.spongeReleaseRepo
                }
            }
        } else if (project.hasProperty('spongeSnapshotRepo')) {
            maven {
                credentials {
                    username = project.spongeUsername
                    password = project.spongePassword
                }
                url project.spongeSnapshotRepo
            }
        }
    }

    publications.register('pluginMaven', MavenPublication) {
        artifact groovydocJar

        pom { pom ->
            name = gradleutils.displayName
            description = project.description

            gradleutils.pom.addRemoteDetails(pom)

            licenses {
                license gradleutils.pom.licenses.MIT
            }
        }
    }
}
